/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Test1 */

#ifndef _Included_test_Test1
#define _Included_test_Test1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Test1
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Test1_sayHi
  (JNIEnv *, jclass);

/*
 * Class:     test_Test1
 * Method:    sayHiToMe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Test1_sayHiToMe
  (JNIEnv *, jclass);

/*
 * Class:     test_Test1
 * Method:    sayHiToMeAndGoodbye
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Test1_sayHiToMeAndGoodbye
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
